initial_positions:
  base: 1.5708
  shoulder: 0.7854
  elbow: 3.14
  wrist_pitch: 3.14
  wrist_roll: 1.5708
  gripper_joint: 0.175

# NOTE: These value don't affect code
  # (commenting entire file out changes nothing when running so far)