default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

joint_limits:

  base:
    has_velocity_limits: true
    max_velocity: 10.0  
    has_acceleration_limits: false
    max_acceleration: 0.0

  shoulder:
    has_velocity_limits: true
    max_velocity: 10.0  
    has_acceleration_limits: false
    max_acceleration: 0.0

  elbow:
    has_velocity_limits: true
    max_velocity: 10.0  
    has_acceleration_limits: false
    max_acceleration: 0.0

  wrist_pitch:
    has_velocity_limits: true
    max_velocity: 10.0  
    has_acceleration_limits: false
    max_acceleration: 0.0

  wrist_roll:
    has_velocity_limits: true
    max_velocity: 10.0  
    has_acceleration_limits: false
    max_acceleration: 0.0

  gripper_movable:
    has_velocity_limits: true
    max_velocity: 10.0  
    has_acceleration_limits: false
    max_acceleration: 0.0