moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - gripper_controller

  arm_controller:
    action_ns: follow_joint_trajectory
    type: follow_joint_trajectory
    default: True
    joints:
      - base
      - shoulder
      - elbow
      - wrist_pitch
      - wrist_roll

  gripper_controller:
    action_ns: follow_joint_trajectory
    type: follow_joint_trajectory
    default: True
    joints:
      - gripper_movable